version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_DATABASE=api-solid
      - POSTGRESQL_PASSWORD=root
